runtime: python38
automatic_scaling:
  max_instances: 1

default_expiration: "365d"

handlers:
- url: /
  static_files: index.html
  upload: index.html
  secure: always
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  secure: always
- url: /index.html
  static_files: index.html
  upload: index.html
  secure: always
- url: /manifest.json
  static_files: manifest.json
  upload: manifest.json
  secure: always
- url: /precache(.*)$
  static_files: precache\1
  upload: precache(.*)$
  secure: always
- url: /privacy.html
  static_files: privacy.html
  upload: privacy.html
  secure: always
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  secure: always
- url: /service-worker.js
  static_files: service-worker.js
  upload: service-worker.js
  expiration: "1d"
  secure: always
- url: /css
  static_dir: css
  secure: always
- url: /fonts
  static_dir: fonts
  secure: always
- url: /img
  static_dir: img
  secure: always
- url: /js
  static_dir: js
  secure: always
