name: Deployment

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: "14.x"
    - run: npm ci
    - run: npm run build
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: "290.0.1"
        project_id: ${{ secrets.GAE_PROJECT }}
        service_account_key: ${{ secrets.GAE_ACCOUNT }}
        export_default_credentials: true
    - run: cd dist && gcloud app deploy --version=2 --quiet
